### ISSUE TITLE
Arithmetic overflow error from WSUS on calling `GetUpdates`

### ISSUE THREAD

**Issue by DanPhonovation** [ralish/PSWsusSpringClean#2]
Fresh WSUS on Server 2019 backed by a SQL AAG Group on a VMWare cluster with 64 cores and 4TB of RAM. VM is a 8 core - 24 GB of RAM.

```
PS C:\WSUSUtility> Invoke-WsusSpringClean -DeclineArchitectures @('arm64', 'ia64')

Beginning WSUS server cleanup (Phase 1) ...

Beginning WSUS server cleanup (Phase 2) ...
[*] Retrieving approved updates ...
[*] Retrieving unapproved updates ...
Exception calling "GetUpdates" with "1" argument(s): "Client found response content type of 'text/html;
charset=utf-8', but expected 'text/xml'.
The request failed with the error message:
--
<!DOCTYPE html>
<html>
    <head>
        <title>Overflow or underflow in the arithmetic operation.</title>
        <meta name="viewport" content="width=device-width" />
        <style>
         body {font-family:"Verdana";font-weight:normal;font-size: .7em;color:black;}
         p {font-family:"Verdana";font-weight:normal;color:black;margin-top: -5px}
         b {font-family:"Verdana";font-weight:bold;color:black;margin-top: -5px}
         H1 { font-family:"Verdana";font-weight:normal;font-size:18pt;color:red }
         H2 { font-family:"Verdana";font-weight:normal;font-size:14pt;color:maroon }
         pre {font-family:"Consolas","Lucida Console",Monospace;font-size:11pt;margin:0;padding:0.5em;line-height:14pt}
         .marker {font-weight: bold; color: black;text-decoration: none;}
         .version {color: gray;}
         .error {margin-bottom: 10px;}
         .expandable { text-decoration:underline; font-weight:bold; color:navy; cursor:pointer; }
         @media screen and (max-width: 639px) {
          pre { width: 440px; overflow: auto; white-space: pre-wrap; word-wrap: break-word; }
         }
         @media screen and (max-width: 479px) {
          pre { width: 280px; }
         }
        </style>
    </head>
    <body bgcolor="white">
            <span><H1>Server Error in '/ApiRemoting30' Application.<hr width=100% size=1 color=silver></H1>
            <h2> <i>Overflow or underflow in the arithmetic operation.</i> </h2></span>
            <font face="Arial, Helvetica, Geneva, SunSans-Regular, sans-serif ">
            <b> Description: </b>An unhandled exception occurred during the execution of the current web request.
Please review the stack trace for more information about the error and where it originated in the code.
            <br><br>
            <b> Exception Details: </b>System.ArithmeticException: Overflow or underflow in the arithmetic
operation.<br><br>
            <b>Source Error:</b> <br><br>
            <table width=100% bgcolor="#ffffcc">
               <tr>
                  <td>
                      <code>
An unhandled exception was generated during the execution of the current web request. Information regarding the origin
and location of the exception can be identified using the exception stack trace below.                      </code>
                  </td>
               </tr>
            </table>
            <br>
            <b>Stack Trace:</b> <br><br>
            <table width=100% bgcolor="#ffffcc">
               <tr>
                  <td>
                      <code><pre>
[ArithmeticException: Overflow or underflow in the arithmetic operation.]
[HttpException (0x80004005): An error occurred while communicating with the remote host. The error code is 0x80070216.]
   System.Web.Hosting.IIS7WorkerRequest.RaiseCommunicationError(Int32 result, Boolean throwOnDisconnect) +4719042
   System.Web.Hosting.IIS7WorkerRequest.FlushCore(Boolean keepConnected, Int32 numBodyFragments, IntPtr[]
bodyFragments, Int32[] bodyFragmentLengths, Int32[] bodyFragmentTypes) +11760354
   System.Web.Hosting.IIS7WorkerRequest.FlushCachedResponse(Boolean isFinal) +764
   System.Web.HttpResponse.UpdateNativeResponse(Boolean sendHeaders) +537
   System.Web.HttpRuntime.FinishRequestNotification(IIS7WorkerRequest wr, HttpContext context,
RequestNotificationStatus& status) +145
</pre>                      </code>
                  </td>
               </tr>
            </table>
            <br>
            <hr width=100% size=1 color=silver>
            <b>Version Information:</b> Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.8.4330.0
            </font>
    </body>
</html>
<!--
[ArithmeticException]: Overflow or underflow in the arithmetic operation.
[HttpException]: An error occurred while communicating with the remote host. The error code is 0x80070216.
   at System.Web.Hosting.IIS7WorkerRequest.RaiseCommunicationError(Int32 result, Boolean throwOnDisconnect)
   at System.Web.Hosting.IIS7WorkerRequest.FlushCore(Boolean keepConnected, Int32 numBodyFragments, IntPtr[]
bodyFragments, Int32[] bodyFragmentLengths, Int32[] bodyFragmentTypes)
   at System.Web.Hosting.IIS7WorkerRequest.FlushCachedResponse(Boolean isFinal)
   at System.Web.HttpResponse.UpdateNativeResponse(Boolean sendHeaders)
   at System.Web.HttpRuntime.FinishRequestNotification(IIS7WorkerRequest wr, HttpContext context,
RequestNotificationStatus& status)
-->
--."
At C:\Program Files\WindowsPowerShell\Modules\PSWsusSpringClean\0.5.0\PSWsusSpringClean.psm1:531 char:5
+     $WsusUnapproved = $UpdateServer.GetUpdates($UpdateScope)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : InvalidOperationException
```

**Comment by ralish** [comment]
That error is coming from WSUS itself and not the PowerShell module. Internally the module is simply calling `GetUpdates` on the .NET instance returned by the `Get-WsusServer` cmdlet. The stack trace you see is being returned by IIS due to something going wrong in the internal processing of WSUS while handling the request.

There's not enough information in the output to have any idea what's going wrong beyond that. I'd suggest starting with:

1. Ensure the WSUS server and underlying Windows system is fully updated. It's possible if that's not the case the issue may already be fixed in an existing cumulative update.
2. Take a look at the logs generated by WSUS at the time of the failed request. It's been a while since I had to debug a WSUS issue, but I'd start by checking for any interesting event logs, and the `C:\Program Files\Update Services\LogFiles` folder.
3. The actual IIS application generating the error is `ApiRemoting30`, so any logs for that web application may also be of use.

**Comment by DanPhonovation** [comment]
I got past this. The best I can ascertain is it had something to do with too large a WSUS database.
